### ISSUE TITLE
?yet another gittip

### ISSUE THREAD

**Issue by techtonik** [tav/gitfund#1]
Hi, @tav 

What is the model? I am most interested how it is different from Gratipay (or Liberapay), but if there is a similarity with any of the existing projects from http://inside.gratipay.com/appendices/see-also/ it would be nice to know.

**Comment by tav** [comment]
Wow, that's an incredible list — thanks to those who have been putting it together!

Some key differences/similarities to some of the sites on that list:
- Unlike say Kickstarter/IndieGogo, GitFund is based on monthly contributions, since software is rarely ever _done_, and tends to require ongoing maintenance and improvements.
- There are no custom rewards since most people aren't that interested in having signed posters or surprise gifts from the creators of the open source projects that they find useful.
- Instead of trying to be a generic crowd-funding platform, it is explicitly focused on supporting open source projects, and as such will be tightly integrated with GitHub.
- Instead of open donations, which suffers from the usual tragedy of the commons problem of "I'm sure someone else will donate", GitFund is based on a sponsorship model with limited number of sponsorship slots per project. The artificial scarcity caused by the limited number of slots will hopefully act as a strong incentive for people to fund projects.
- While I strongly believe in peer funding and even own the domain `peerfund.com`, GitFund will primarily target organisations as the main sponsors for projects. As things stand, organisations (from small digital agencies to large tech companies) are the biggest beneficiaries of open source software, but rarely contribute back fairly.
- All sponsorships will be public. Sponsors could use this as a form of advertisement if they like, e.g. if you were a sponsor of Django, and the GitFund widget was embedded on the Django site, you could use it to say "We're hiring Django developers in London. Apply here!".
- While sponsors can upvote issues/milestones that they care about, there will be no "pay-for-features" aspect like on BountySource, or anything that takes control away from the developers of the project being sponsored.
- Unlike say GoFundMe and various other crowdfunding sites, the aim isn't to be a billion dollar unicorn startup. Besides the fees charged by the payment processors, there will be 0% fee charged by the platform itself. Instead, GitFund will use GitFund itself to get sponsors to cover the running costs.

More concretely about the model: there are three tiers of sponsorship, and for each tier, each project gets to define the number of available slots and the monthly sponsorship amount, e.g.

| Tier | Slots | Cost |
| :-: | :-: | :-: |
| 1 | 5 | $200/month |
| 2 | 25 | $40/month |
| 3 | 100 | $10/month |

A well established project like Django will no doubt be able to raise a lot more than a project like LightTable during the initial inception stage. But hopefully over time, we'll collectively get a better understanding of the appropriate pricing levels to use.

With regards to Gratipay in particular, despite the differences in the model, there is a decent amount of overlap and I imagine both projects come from the same set of shared values/ethos.

In fact, the Gratipay model is much closer to [my long term vision of Pecus (since renamed to Appreciation)](http://thruflo.com/post/6415771652/tav-describes-pecus-html) than GitFund. But to really make it work, I came to conclusion that the Appreciation model has to be tightly integrated with how we interact digitally and also needs a much better payment distribution mechanism than what we have now.

And thus why I'm also working on [Ampify](https://github.com/tav/ampify) as a replacement for the Web which has, amongst other things, a payments mechanism tightly integrated. But that's probably a conversation for some other time.

In the meantime, I felt GitFund model has better chance of succeeding and will hopefully enable a cultural shift in the open source community to better funding the various projects that we all depend on. Anyway, hope that answers your question. What do you think?

**Comment by techtonik** [comment]
Need some time to commend on this. Quick toughs - slots idea is neat - I like it. Focus on companies as money owners is good, but it would be nice if that still could pass through individuals who chosen to support the case.

**Comment by tav** [comment]
Not sure I understood what you meant by "if that still could pass through individuals who chosen to support the case". Do you mean that it would be nice if individuals could still support projects? If so, sure, sponsors don't need to be organisations, they could be individuals too.

**Comment by techtonik** [comment]
@tav that means that individuals **inside** the companies should affect who is supported. In big companies there are a lot of money, but nobody contributes to open source, because all requests should go through some kind of corporate censorship. If a person could direct their own money through the company, that will make them feel good about being there.
